// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX0EVzRXbs0s9lcFFDz65QkOgBHGDZgJA',
    appId: '1:289462543356:web:582669df306692c559c879',
    messagingSenderId: '289462543356',
    projectId: 'vital-track-gemini',
    authDomain: 'vital-track-gemini.firebaseapp.com',
    storageBucket: 'vital-track-gemini.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSV9avzXnqJDnMzKV4MqarCEJx-mSRUQ0',
    appId: '1:289462543356:android:7f556879b8401a7159c879',
    messagingSenderId: '289462543356',
    projectId: 'vital-track-gemini',
    storageBucket: 'vital-track-gemini.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU2z4s7A5Qrk_9t_7ZVoS-c4Fu_mglXJ8',
    appId: '1:289462543356:ios:b2daa896ae2c580559c879',
    messagingSenderId: '289462543356',
    projectId: 'vital-track-gemini',
    storageBucket: 'vital-track-gemini.firebasestorage.app',
    iosBundleId: 'gemini.mithos.vitalTrack',
  );
}
